"""
Configuration builders for Kickstart and GRUB files.
Handles the generation of installation configuration files.
"""

from dataclasses import dataclass
from pathlib import Path

from models.kickstart import KickstartConfig
from services import kickstart_builder


@dataclass(frozen=True)
class GrubEntry:
    """Represents a GRUB menu entry configuration."""

    title: str
    prelines: tuple[str, ...]
    linux_cmd: str
    initrd_cmd: str
    is_in_submenu: bool


def _build_load_video_function() -> str:
    """Build the GRUB load_video function string."""
    modules = (
        "efi_gop",
        "efi_uga",
        "video_bochs",
        "video_cirrus",
        "all_video",
    )
    lines = ["function load_video {"]
    for module in modules:
        lines.append(f"  insmod {module}")
    lines.append("}")
    return "\n".join(lines)


def build_autoinstall_ks_file(
    kickstart_config: KickstartConfig,
) -> str:
    """Build a Kickstart file for automated Fedora installation."""
    return kickstart_builder.build_autoinstall_ks_file(kickstart_config)


def build_base_ks_file(kickstart_config: KickstartConfig) -> str:
    """Build base Kickstart file content."""
    return kickstart_builder.build_base_ks_file(kickstart_config)


def write_ks_files(kickstart_config: KickstartConfig, base_path: Path) -> None:
    """Write Kickstart files (`ks.cfg` and include files) to disk."""
    kickstart_builder.write_ks_files(kickstart_config, base_path)


def build_grub_cfg_file(
    root_partition_label: str,
    is_autoinst: bool = False,
) -> str:
    """
    Build a GRUB configuration file for the installer.

    Args:
        root_partition_label: Label of the root partition
        is_autoinst: Whether to include auto-install menu entry

    Returns:
        Generated GRUB configuration file content
    """
    # Define GRUB entries
    entries = [
        GrubEntry(
            title="Install Fedora",
            prelines=(),
            linux_cmd=f"linux /images/pxeboot/vmlinuz inst.stage2=hd:LABEL={root_partition_label} rd.live.check quiet",
            initrd_cmd="initrd /images/pxeboot/initrd.img",
            is_in_submenu=True,
        ),
        GrubEntry(
            title="Install Fedora (RAM-Boot)",
            prelines=(),
            linux_cmd=f"linux /images/pxeboot/vmlinuz inst.stage2=hd:LABEL={root_partition_label} rd.live.check rd.live.ram quiet",
            initrd_cmd="initrd /images/pxeboot/initrd.img",
            is_in_submenu=True,
        ),
        GrubEntry(
            title="Install Fedora in basic graphics mode",
            prelines=(),
            linux_cmd=f"linux /images/pxeboot/vmlinuz inst.stage2=hd:LABEL={root_partition_label} nomodeset quiet",
            initrd_cmd="initrd /images/pxeboot/initrd.img",
            is_in_submenu=True,
        ),
        GrubEntry(
            title="Rescue a Fedora system",
            prelines=(),
            linux_cmd=f"linux /images/pxeboot/vmlinuz inst.stage2=hd:LABEL={root_partition_label} inst.rescue quiet",
            initrd_cmd="initrd /images/pxeboot/initrd.img",
            is_in_submenu=True,
        ),
    ]

    # Add auto-install entry if enabled
    if is_autoinst:
        linux_cmd = f"linux /images/pxeboot/vmlinuz inst.stage2=hd:LABEL={root_partition_label} rd.live.check inst.ks=hd:LABEL={root_partition_label} quiet"
        entries.insert(
            0,
            GrubEntry(
                title="Auto Install Fedora",
                prelines=(),
                linux_cmd=linux_cmd,
                initrd_cmd="initrd /images/pxeboot/initrd.img",
                is_in_submenu=False,
            ),
        )

    # Build GRUB lines
    grub_lines = [
        "### Grub configuration generated by WinGone ###",
        'set default="0"',
        _build_load_video_function(),
        "load_video",
        "set gfxpayload=keep",
        "insmod gzio",
        "insmod part_gpt",
        "insmod ext2",
        "set timeout=5",
        f"search --no-floppy --set=root -l '{root_partition_label}'",
    ]

    # Separate entries into main and submenu
    main_entries = [entry for entry in entries if not entry.is_in_submenu]
    submenu_entries = [entry for entry in entries if entry.is_in_submenu]

    # Add main menu entries
    for entry in main_entries:
        menu_lines = [
            f"""menuentry '{entry.title}' --class fedora --class gnu-linux --class gnu --class os {{"""
        ]
        menu_lines.extend(f"    {line}" for line in entry.prelines)
        menu_lines.append(f"    {entry.linux_cmd}")
        menu_lines.append(f"    {entry.initrd_cmd}")
        menu_lines.append("}")
        grub_lines.extend(menu_lines)

    # Add troubleshooting submenu if there are submenu entries
    if submenu_entries:
        grub_lines.append("submenu 'Other Options -->' {")
        for entry in submenu_entries:
            menu_lines = [
                f"""    menuentry '{entry.title}' --class fedora --class gnu-linux --class gnu --class os {{"""
            ]
            menu_lines.extend(f"        {line}" for line in entry.prelines)
            menu_lines.append(f"        {entry.linux_cmd}")
            menu_lines.append(f"        {entry.initrd_cmd}")
            menu_lines.append("    }")
            grub_lines.extend(menu_lines)
        grub_lines.append("}")

    return "\n".join(grub_lines)
